# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: >
  Hey there! You didn't give us a whole lot of info about this issue.
  We would love if you could provide more details about what you're trying to accomplish here.