# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14

# Issues with these labels will never be considered stale
exemptLabels:
   - v3
   - help-wanted
   - P0
   - P1
   - bug
   - enhancement
   - proposal
   - feature-request

# Set to true to ignore issues in a project (defaults to false)
exemptProjects: true

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed in a week if no further activity occurs.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  Closing this issue after a prolonged period of inactivity. If you still think this issue is relevant, please feel free to ping a maintainer or leave a comment.
