trigger:
- v3
- feature/*
queue:
  name: DocFX
steps:
- powershell: ./impact.ps1
  env:
    OP_BUILD_USER_TOKEN: $(OpBuildUserToken)
    GITHUB_BASIC_AUTH: $(GitHubBasicAuth)
    SYSTEM_ACCESS_TOKEN: $(System.AccessToken)
  displayName: Impact Test

- powershell: ./build.ps1
  displayName: Build

- task: NuGetCommand@2
  condition: >-
    and(succeeded(), or(
      eq(variables['Build.SourceBranch'], 'refs/heads/v3'),
      startsWith(variables['Build.SourceBranch'], 'feature/')))
  displayName: Push to Sandbox MyGet Feed
  inputs:
    command: push
    packagesToPush: drop/**/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: myget.docfx-v3-sandbox

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/v3'))
  displayName: Push to Production MyGet Feed
  inputs:
    command: push
    packagesToPush: drop/**/*.nupkg
    nuGetFeedType: external
    publishFeedCredentials: myget.docfx-v3
