# daily trigger
trigger:
  batch: true
  branches:
    include:
    - v3
    - v3-release
  paths:
    exclude:
    - docs/designs/*
pr: none

variables:
  Codeql.Enabled: true

pool:
  vmImage: 'windows-2019'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core sdk 6.0'
  inputs:
    packageType: sdk
    version: 6.0.x

- task: DotNetCoreCLI@2
  displayName: Dotnet build
  inputs:
    command: 'build'
    projects: '**\*.csproj'
    arguments: '-c Release'
