# This YAML is used for the docfx v2 main release CI (https://dev.azure.com/ceapex/Engineering/_build?definitionId=1503&_a=summary)

variables:
- group: docfx-v2-pipeline-kv
- name: NUGETEXE
  value: nuget

pool:
  name: 1ES-Pool
  demands: ImageOverride -equals MMS2019

steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core sdk required for ESRPCodeSigning'
  inputs:
    packageType: sdk
    version: '2.1.811'

- task: UseDotNet@2
  displayName: 'Install .NET Core sdk required for docfx'
  inputs:
    packageType: sdk
    version: '5.0.100'

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'
  inputs:
    versionSpec: 5.9.1

- task: PowerShell@2
  displayName: 'main build'
  inputs:
    pwsh: true
    failOnStderr: true
    filePath: 'tools\Deployment\deploy.ps1'
    arguments: '-main'
  env:
    TOKEN: $(ServiceAccountGithubToken)

- task: UseDotNet@2
  displayName: 'Install .NET Core sdk required for ESRPCodeSigning'
  inputs:
    packageType: sdk
    version: '2.1.811'

- task: EsrpCodeSigning@1
  displayName: Sign docfx executables and dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\Microsoft.DocAsCode.*.dll
        **\*.exe
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: EsrpCodeSigning@1
  displayName: Sign dependent dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\*.dll
        !**\System.*.dll
        !**\Microsoft.!(DocAsCode).*.dll
        !**\NuGet.*.dll
        !**\FSharp.Core.*.dll
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "Append",
              "parameterValue": "/as"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: PowerShell@2
  displayName: 'main pack'
  inputs:
    pwsh: true
    failOnStderr: true
    filePath: 'tools\Deployment\deploy.ps1'
    arguments: '-main -targets pack'

- task: EsrpCodeSigning@1
  displayName: 'Sign NuGet packages'
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: 'artifacts\Release'
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
             {
                 "KeyCode" : "CP-401405",
                 "OperationSetCode" : "NuGetSign",
                 "Parameters" : [
                    {
                      "parameterName": "TimeStamp",
                      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                    },
                    {
                      "parameterName": "FileDigest",
                      "parameterValue": "/fd \"SHA256\""
                    }
                 ],
                 "ToolName" : "sign",
                 "ToolVersion" : "1.0"
             },
             {
                 "KeyCode" : "CP-401405",
                 "OperationSetCode" : "NuGetVerify",
                 "Parameters" : [],
                 "ToolName" : "sign",
                 "ToolVersion" : "1.0"
             }
      ]
     
    SessionTimeout: 20

- task: PowerShell@2
  displayName: 'main release'
  inputs:
    pwsh: true
    failOnStderr: true
    filePath: 'tools\Deployment\deploy.ps1'
    arguments: '-main -targets release'
  env:
    NUGETAPIKEY: $(NugetAPIKey)
    CHOCO_TOKEN: $(ChocoleteyPublishToken)
    TOKEN: $(ServiceAccountGithubToken)

- task: ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))