pool:
  name: Hosted Windows 2019 with VS2019

steps:

- task: NodeTool@0
  displayName: 'Use Node 8.x'
  inputs:
    versionSpec: 8.x

- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: CmdLine@1
  displayName: 'npm install'
  inputs:
    filename: npm
    arguments: install
    workingFolder: tools/Deployment

- task: CmdLine@1
  displayName: 'tsc compile'
  inputs:
    filename: node
    arguments: '.\node_modules\typescript\bin\tsc'
    workingFolder: tools/Deployment

- task: CmdLine@1
  displayName: 'gulp build'
  inputs:
    filename: node
    arguments: '.\node_modules\gulp\bin\gulp.js master:build'
    workingFolder: tools/Deployment

- task: EsrpCodeSigning@1
  displayName: Sign docfx executables and dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\Microsoft.DocAsCode.*.dll
        **\*.exe
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-230012",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: EsrpCodeSigning@1
  displayName: Sign dependent dlls
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: '$(Build.SourcesDirectory)/target/Release'
    Pattern: |
        **\*.dll
        !**\System.*.dll
        !**\Microsoft.*.dll
        !**\NuGet.*.dll
        !**\FSharp.Core.*.dll
    UseMinimatch: true
    signConfigType: inlineSignParams
    inlineOperation: |
     [
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "Microsoft"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "http://www.microsoft.com"
            },
            {
              "parameterName": "Append",
              "parameterValue": "/as"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd \"SHA256\""
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        },
        {
          "KeyCode": "CP-231522",
          "OperationSetCode": "SigntoolVerify",
          "Parameters": [
            {
              "parameterName": "VerifyAll",
              "parameterValue": "/all"
            }
          ],
          "ToolName": "sign",
          "ToolVersion": "1.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'

- task: CmdLine@1
  displayName: 'gulp pack'
  inputs:
    filename: node
    arguments: '.\node_modules\gulp\bin\gulp.js master:pack'
    workingFolder: tools/Deployment

- task: EsrpCodeSigning@1
  displayName: 'Sign NuGet packages'
  inputs:
    ConnectedServiceName: 'CodeSigning-APEX'
    FolderPath: 'artifacts\Release'
    Pattern: '*.nupkg'
    signConfigType: inlineSignParams
    inlineOperation: |
     [
             {
                 "KeyCode" : "CP-401405",
                 "OperationSetCode" : "NuGetSign",
                 "Parameters" : [
                    {
                      "parameterName": "TimeStamp",
                      "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                    },
                    {
                      "parameterName": "FileDigest",
                      "parameterValue": "/fd \"SHA256\""
                    }
                 ],
                 "ToolName" : "sign",
                 "ToolVersion" : "1.0"
             },
             {
                 "KeyCode" : "CP-401405",
                 "OperationSetCode" : "NuGetVerify",
                 "Parameters" : [],
                 "ToolName" : "sign",
                 "ToolVersion" : "1.0"
             }
      ]
     
    SessionTimeout: 20

- task: CmdLine@1
  displayName: 'gulp release'
  inputs:
    filename: node
    arguments: '.\node_modules\gulp\bin\gulp.js master:release'
    workingFolder: tools/Deployment
  env:
    NUGETAPIKEY: $(NUGETAPIKEY)
