using System.Text.RegularExpressions;
using Microsoft.Extensions.Logging;

namespace BuildFromProject;

public static partial class SourceGenerator
{
    /// <summary>
    /// Logger API that generated by LoggerMessageGenerator.
    /// </summary>
    [LoggerMessage(EventId = 0, Level = LogLevel.Critical, Message = "Log: {text}")]
    public static partial void Log(ILogger logger, string text);

    /// <summary>
    /// Regex that generated by SourceGenerator.
    /// </summary>
    [GeneratedRegex("abc|def", RegexOptions.IgnoreCase)]
    public static partial Regex GeneratedRegex();
}
