// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.ComponentModel;
using Spectre.Console.Cli;

#nullable enable

namespace Docfx;

[Description("Cleanup temporary files that are generated by docfx")]
internal class CleanCommandOptions : LogOptions
{
    [Description("Path to docfx.json")]
    [CommandArgument(0, "[config]")]
    public required string ConfigFile { get; set; }

    [Description("If set to true, skip file/directory delete operations")]
    [CommandOption("--dryRun")]
    public bool DryRun { get; set; }
}
