// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.IO.Compression;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace Docfx.Dotnet.Tests;

public class GeneratedCodeDetectorTest
{
    [Theory]
    [InlineData("// <auto-generated/>\nclass C {}", true)]
    [InlineData("\uFEFF// <auto-generated/>\nclass C {}", true)]
    [InlineData("// License\n// <auto-generated>\nclass C {}", true)]
    [InlineData("/*\n * <auto-generated />\n */\nclass C {}", true)]
    [InlineData("/// <auto-generated/>\nclass C {}", false)]
    [InlineData("// <AUTO-GENERATED/>\nclass C {}", true)]
    [InlineData("// <autogenerated/>\nclass C {}", true)]
    [InlineData("// Example: <auto-generated/> is a marker.\nclass C {}", false)]
    [InlineData("/* Example:\n * <auto-generated/>\n */\nclass C {}", false)]
    [InlineData("/// <code>\n/// <auto-generated/>\n/// </code>\nclass C {}", false)]
    [InlineData("// <auto-generated-example/>\nclass C {}", false)]
    [InlineData("class C { string S = \"<auto-generated/>\"; }", false)]
    [InlineData("class C { // <auto-generated/>\n}", false)]
    [InlineData("class C {}\n// <auto-generated/>", false)]
    public void RecognizesOnlyLeadingCSharpCommentMarkers(string text, bool expected)
    {
        Assert.Equal(expected, GeneratedCodeDetector.HasGeneratedHeader(text, LanguageNames.CSharp));
        Assert.Equal(expected, GeneratedCodeDetector.HasGeneratedHeader(CSharpSyntaxTree.ParseText(text)));
    }

    [Theory]
    [InlineData("' <auto-generated/>\nPublic Class C\nEnd Class", true)]
    [InlineData("''' <auto-generated/>\nPublic Class C\nEnd Class", false)]
    [InlineData("' License\n' <auto-generated>\nPublic Class C\nEnd Class", true)]
    [InlineData("' Example: <auto-generated/>\nPublic Class C\nEnd Class", false)]
    [InlineData("Public Class C\n' <auto-generated/>\nEnd Class", false)]
    [InlineData("Public Class C\nDim x As String = \"<auto-generated/>\"\nEnd Class", false)]
    public void RecognizesOnlyLeadingVisualBasicCommentMarkers(string text, bool expected)
    {
        Assert.Equal(expected, GeneratedCodeDetector.HasGeneratedHeader(text, LanguageNames.VisualBasic));
        Assert.Equal(expected, GeneratedCodeDetector.HasGeneratedHeader(Microsoft.CodeAnalysis.VisualBasic.VisualBasicSyntaxTree.ParseText(text)));
    }

    [Theory]
    [InlineData(false, false)]
    [InlineData(true, false)]
    [InlineData(false, true)]
    [InlineData(true, true)]
    public void ReadsCompressedAndUncompressedEmbeddedHeaders(bool compressed, bool unicode)
    {
        var encoding = unicode ? Encoding.Unicode : Encoding.UTF8;
        var source = encoding.GetPreamble().Concat(encoding.GetBytes("// <auto-generated/>\nclass C {}")).ToArray();
        var blob = EmbeddedBlob(source, compressed);
        Assert.True(GeneratedCodeDetector.HasGeneratedEmbeddedHeader(blob, new("3f5162f8-07c6-11d3-9053-00c04fa302a1")));
        Assert.False(GeneratedCodeDetector.HasGeneratedEmbeddedHeader(blob, Guid.Empty));
        var vb = EmbeddedBlob(Encoding.UTF8.GetBytes("' <auto-generated/>\nPublic Class C\nEnd Class"), compressed);
        Assert.True(GeneratedCodeDetector.HasGeneratedEmbeddedHeader(vb, new("3a12d0b8-c26c-11d0-b442-00a0244a1dd2")));
    }

    [Theory]
    [InlineData(-1)]
    [InlineData(1)]
    public void RejectsIncorrectCompressedLength(int sizeChange)
    {
        var source = Encoding.UTF8.GetBytes("// <auto-generated/>\nclass C {}");
        var blob = EmbeddedBlob(source, compressed: true);
        BitConverter.GetBytes(source.Length + sizeChange).CopyTo(blob, 0);
        Assert.Throws<InvalidDataException>(() => GeneratedCodeDetector.HasGeneratedEmbeddedHeader(blob, new("3f5162f8-07c6-11d3-9053-00c04fa302a1")));
    }

    [Fact]
    public void RejectsTruncatedAndUnsupportedEmbeddedFormats()
    {
        var language = new Guid("3f5162f8-07c6-11d3-9053-00c04fa302a1");
        Assert.Throws<InvalidDataException>(() => GeneratedCodeDetector.HasGeneratedEmbeddedHeader([0, 0], language));
        Assert.Throws<InvalidDataException>(() => GeneratedCodeDetector.HasGeneratedEmbeddedHeader([255, 255, 255, 255], language));
        Assert.Throws<DecoderFallbackException>(() => GeneratedCodeDetector.HasGeneratedEmbeddedHeader([0, 0, 0, 0, 255], language));
    }

    [Theory]
    [InlineData(false)]
    [InlineData(true)]
    public void MarkedPartialDeclarationDoesNotHideHandwrittenMembers(bool sameFile)
    {
        const string generated = """
            namespace Example;
            [System.CodeDom.Compiler.GeneratedCode("test", "1")]
            public partial class C { public void Generated() {} }
            """;
        const string handwritten = "public partial class C { public void Handwritten() {} }";
        var tree = CSharpSyntaxTree.ParseText(generated + (sameFile ? "\n" + handwritten : ""), path: "/repo/Generated.cs");
        var compilation = CompilationHelper.CreateCompilationFromCSharpCode("", new Dictionary<string, string>(), "test")
            .RemoveAllSyntaxTrees().AddSyntaxTrees(tree);
        if (!sameFile)
            compilation = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText("namespace Example; " + handwritten, path: "/repo/Handwritten.cs"));
        var type = compilation.GetTypeByMetadataName("Example.C");
        var generatedMethod = Assert.Single(type.GetMembers("Generated"));
        var handwrittenMethod = Assert.Single(type.GetMembers("Handwritten"));
        var filter = new SourceLinkFilter([], excludeGenerated: true);
        Assert.True(filter.IsExcluded(generatedMethod, Assert.Single(generatedMethod.DeclaringSyntaxReferences)));
        Assert.False(filter.IsExcluded(handwrittenMethod, Assert.Single(handwrittenMethod.DeclaringSyntaxReferences)));
        Assert.False(new SourceLinkFilter([]).IsExcluded(generatedMethod, Assert.Single(generatedMethod.DeclaringSyntaxReferences)));
    }

    [Fact]
    public void GeneratorImplementationAttributeDoesNotMarkItsSourceAsGenerated()
    {
        var compilation = CompilationHelper.CreateCompilationFromCSharpCode(
            "[Microsoft.CodeAnalysis.Generator] public class MyGenerator { public void Execute() {} }",
            new Dictionary<string, string>(), "test", MetadataReference.CreateFromFile(typeof(GeneratorAttribute).Assembly.Location));
        Assert.Empty(compilation.GetDiagnostics().Where(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error));
        var type = compilation.GetTypeByMetadataName("MyGenerator");
        var method = Assert.Single(type.GetMembers("Execute"));
        var filter = new SourceLinkFilter([], excludeGenerated: true);
        Assert.False(filter.IsExcluded(type, Assert.Single(type.DeclaringSyntaxReferences)));
        Assert.False(filter.IsExcluded(method, Assert.Single(method.DeclaringSyntaxReferences)));
    }

    [Fact]
    public void MarkedSingleTypeIncludesItsUnannotatedMembers()
    {
        var compilation = CompilationHelper.CreateCompilationFromCSharpCode(
            """
            [System.CodeDom.Compiler.GeneratedCode("test", "1")]
            public class C { public void Method() {} }
            """, new Dictionary<string, string>(), "test");
        var type = compilation.GetTypeByMetadataName("C");
        var method = Assert.Single(type.GetMembers("Method"));
        Assert.Empty(method.GetAttributes());
        var filter = new SourceLinkFilter([], excludeGenerated: true);
        Assert.True(filter.IsExcluded(type, Assert.Single(type.DeclaringSyntaxReferences)));
        Assert.True(filter.IsExcluded(method, Assert.Single(method.DeclaringSyntaxReferences)));
        Assert.False(new SourceLinkFilter([]).IsExcluded(method, Assert.Single(method.DeclaringSyntaxReferences)));
    }

    [Fact]
    public void VisualBasicMarkedTypeIncludesItsUnannotatedMembers()
    {
        var compilation = CompilationHelper.CreateCompilationFromVBCode(
            """
            <System.CodeDom.Compiler.GeneratedCode("test", "1")>
            Public Class C
                Public Sub Method()
                End Sub
            End Class
            """, new Dictionary<string, string>(), "test");
        var type = compilation.GetTypeByMetadataName("C");
        var method = Assert.Single(type.GetMembers("Method"));
        var filter = new SourceLinkFilter([], excludeGenerated: true);
        Assert.True(filter.IsExcluded(type, Assert.Single(type.DeclaringSyntaxReferences)));
        Assert.True(filter.IsExcluded(method, Assert.Single(method.DeclaringSyntaxReferences)));
    }

    [Fact]
    public void PartialTypeSelectsUnmarkedSourceButRetainsExcludedMemberPosition()
    {
        var handwritten = CSharpSyntaxTree.ParseText("public partial class C { public void Keep() {} }", path: "/repo/Handwritten.cs");
        var generated = CSharpSyntaxTree.ParseText("// <auto-generated/>\npublic partial class C { public void Generated() {} }", path: "/repo/Generated.cs");
        var compilation = CompilationHelper.CreateCompilationFromCSharpCode("", new Dictionary<string, string>(), "test")
            .RemoveAllSyntaxTrees().AddSyntaxTrees(handwritten, generated);
        var type = compilation.GetTypeByMetadataName("C");
        Assert.Equal("/repo/Generated.cs", VisitorHelper.GetSourceDetail(type, compilation).Path);
        var filter = new SourceLinkFilter([], excludeGenerated: true);
        Assert.Equal("/repo/Handwritten.cs", VisitorHelper.GetSourceDetail(type, compilation, filter).Path);
        var member = VisitorHelper.GetSourceDetail(Assert.Single(type.GetMembers("Generated")), compilation, filter);
        Assert.Equal("/repo/Generated.cs", member.Path);
        Assert.Equal(1, member.StartLine);
        Assert.Null(member.Remote);
        Assert.Null(member.Href);
        Assert.Equal("/repo/Generated.cs", VisitorHelper.GetSourceDetail(type, compilation).Path);
    }

    private static byte[] EmbeddedBlob(byte[] source, bool compressed)
    {
        using var blob = new MemoryStream();
        using var writer = new BinaryWriter(blob, Encoding.UTF8, leaveOpen: true);
        writer.Write(compressed ? source.Length : 0);
        if (compressed)
        {
            using var deflate = new DeflateStream(blob, CompressionLevel.Optimal, leaveOpen: true);
            deflate.Write(source);
        }
        else
        {
            writer.Write(source);
        }
        return blob.ToArray();
    }
}
