// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;
using System.Text.Json;
using Docfx.Common;
using Docfx.DataContracts.ManagedReference;
using Docfx.Tests.Common;
using Xunit;

namespace Docfx.Dotnet.Tests;

[Collection("docfx STA")]
public class SourceLinkConfigurationTest : TestBase
{
    [Theory]
    [InlineData("mref")]
    [InlineData("apiPage")]
    [InlineData("markdown")]
    public async Task ExcludesSourceLinksWithoutRemovingApisOrCodeIncludes(string outputFormat)
    {
        var folder = Path.GetFullPath(GetRandomFolder());
        RunGit(folder, "init --quiet --initial-branch=main");
        RunGit(folder, "remote add origin https://github.com/dotnet/docfx.git");
        CreateFile("Main.cs",
            """
            namespace Example;
            public partial class Widget
            {
                public void Keep() { }
            }
            """, folder);
        CreateFile("Generated/Api.cs",
            """
            // <auto-generated/>
            namespace Example;
            /// <summary><code source="type-example.txt" /></summary>
            public partial class Widget
            {
                /// <summary><code source="example.txt" /></summary>
                [System.CodeDom.Compiler.GeneratedCode("ExampleGenerator", "1.0")]
                public void Generated() { }
            }
            """, folder);
        CreateFile("Generated/example.txt", "return 42;", folder);
        CreateFile("Generated/type-example.txt", "var widget = new Widget();", folder);

        var configPath = Path.Combine(folder, "docfx.json");
        foreach (var dest in new[] { "default", "excluded", "restored" })
        {
            await File.WriteAllTextAsync(configPath, JsonSerializer.Serialize(new
            {
                metadata = new[]
                {
                    new
                    {
                        src = new[] { new { files = new[] { "Main.cs", "Generated/Api.cs" } } },
                        dest,
                        outputFormat,
                        sourceLinkExclude = dest == "excluded" ? new[] { "**/Generated/**" } : [],
                    },
                },
            }));
            var sourcePaths = new List<string>();
            await DotnetApiCatalog.GenerateManagedReferenceYamlFiles(configPath, new()
            {
                SourceUrl = source =>
                {
                    sourcePaths.Add(source.Path);
                    return "https://github.com/dotnet/docfx/blob/main/" + source.Path;
                },
            });

            var path = Path.Combine(folder, dest, "Example.Widget" + (outputFormat == "markdown" ? ".md" : ".yml"));
            var content = await File.ReadAllTextAsync(path);
            Assert.Contains("Generated()", content);
            Assert.Contains("Keep()", content);
            Assert.Contains("return 42;", content);
            Assert.Contains("var widget = new Widget();", content);
            if (outputFormat == "mref")
            {
                var page = YamlUtility.Deserialize<PageViewModel>(path);
                var generated = Assert.Single(page.Items, item => item.Uid == "Example.Widget.Generated");
                var keep = Assert.Single(page.Items, item => item.Uid == "Example.Widget.Keep");
                Assert.NotNull(keep.Source.Remote);
                Assert.NotNull(generated.Source.Path);
                Assert.Equal(dest != "excluded", generated.Source.Remote is not null);
                Assert.Null(generated.Source.Href);
            }
            else
            {
                Assert.Contains("Main.cs", sourcePaths);
                Assert.Equal(dest != "excluded", sourcePaths.Contains("Generated/Api.cs"));
                if (outputFormat == "apiPage")
                {
                    Assert.Contains("https://github.com/dotnet/docfx/blob/main/Main.cs", content);
                    Assert.Equal(dest != "excluded", content.Contains("https://github.com/dotnet/docfx/blob/main/Generated/Api.cs"));
                }
            }
        }
    }

    private static void RunGit(string folder, string arguments)
    {
        using var stdout = new MemoryStream();
        using var stderr = new MemoryStream();
        using var stdoutWriter = new StreamWriter(stdout);
        using var stderrWriter = new StreamWriter(stderr);
        var exitCode = CommandUtility.RunCommand(new()
        {
            Name = "git",
            Arguments = arguments,
            WorkingDirectory = folder,
        }, stdoutWriter, stderrWriter);
        stdoutWriter.Flush();
        stderrWriter.Flush();
        Assert.True(exitCode == 0, Encoding.UTF8.GetString(stderr.ToArray()));
    }
}
