// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;
using System.Text.Json;
using Docfx.Common;
using Docfx.DataContracts.ManagedReference;
using Docfx.Tests.Common;
using Xunit;

namespace Docfx.Dotnet.Tests;

[Collection("docfx STA")]
public class SourceLinkConfigurationTest : TestBase
{
    [Theory]
    [InlineData("mref", "Generated")]
    [InlineData("apiPage", "Generated")]
    [InlineData("markdown", "Generated")]
    [InlineData("mref", "obj/Generated")]
    [InlineData("apiPage", "obj/Generated")]
    [InlineData("markdown", "obj/Generated")]
    public async Task ExcludesSourceLinksWithoutRemovingApisOrCodeIncludes(string outputFormat, string generatedFolder)
    {
        var folder = Path.GetFullPath(GetRandomFolder());
        RunGit(folder, "init --quiet --initial-branch=main");
        RunGit(folder, "remote add origin https://github.com/dotnet/docfx.git");
        CreateFile("Main.cs",
            """
            namespace Example;
            public partial class Widget
            {
                public void Keep() { }
            }
            """, folder);
        var generatedPath = generatedFolder + "/Api.cs";
        CreateFile(generatedPath,
            """
            // <auto-generated/>
            namespace Example;
            /// <summary><code source="type-example.txt" /></summary>
            public partial class Widget
            {
                /// <summary><code source="example.txt" /></summary>
                [System.CodeDom.Compiler.GeneratedCode("ExampleGenerator", "1.0")]
                public void Generated() { }
            }
            """, folder);
        CreateFile(generatedFolder + "/example.txt", "return 42;", folder);
        CreateFile(generatedFolder + "/type-example.txt", "var widget = new Widget();", folder);

        var configPath = Path.Combine(folder, "docfx.json");
        foreach (var dest in new[] { "default", "excluded", "all-excluded", "restored" })
        {
            await File.WriteAllTextAsync(configPath, JsonSerializer.Serialize(new
            {
                metadata = new[]
                {
                    new
                    {
                        src = new[] { new { files = new[] { "Main.cs", generatedPath } } },
                        dest,
                        outputFormat,
                        sourceLinkExclude = dest switch
                        {
                            "excluded" => new[] { "**/Generated/**" },
                            "all-excluded" => ["**/*.cs"],
                            _ => [],
                        },
                    },
                },
            }));
            var sourcePaths = new List<string>();
            await DotnetApiCatalog.GenerateManagedReferenceYamlFiles(configPath, new()
            {
                SourceUrl = source =>
                {
                    sourcePaths.Add(source.Path);
                    return "https://github.com/dotnet/docfx/blob/main/" + source.Path;
                },
            });

            var path = Path.Combine(folder, dest, "Example.Widget" + (outputFormat == "markdown" ? ".md" : ".yml"));
            var content = await File.ReadAllTextAsync(path);
            Assert.Contains("Generated()", content);
            Assert.Contains("Keep()", content);
            Assert.Contains("return 42;", content);
            Assert.Contains("var widget = new Widget();", content);
            var allExcluded = dest == "all-excluded";
            var expectGeneratedLink = !allExcluded && dest != "excluded" && generatedFolder == "Generated";
            if (outputFormat == "mref")
            {
                var page = YamlUtility.Deserialize<PageViewModel>(path);
                var type = Assert.Single(page.Items, item => item.Uid == "Example.Widget");
                var generated = Assert.Single(page.Items, item => item.Uid == "Example.Widget.Generated");
                var keep = Assert.Single(page.Items, item => item.Uid == "Example.Widget.Keep");
                Assert.Equal(allExcluded ? null : expectGeneratedLink ? generatedPath : "Main.cs", type.Source.Remote?.Path);
                Assert.Equal(expectGeneratedLink || allExcluded ? 3 : 1, type.Source.StartLine);
                Assert.NotNull(type.Source.Path);
                Assert.Equal(!allExcluded, keep.Source.Remote is not null);
                Assert.NotNull(generated.Source.Path);
                Assert.Equal(expectGeneratedLink, generated.Source.Remote is not null);
                Assert.Null(generated.Source.Href);
            }
            else
            {
                Assert.Equal(!allExcluded, sourcePaths.Contains("Main.cs"));
                Assert.Equal(expectGeneratedLink, sourcePaths.Contains(generatedPath));
                if (allExcluded)
                    Assert.Empty(sourcePaths);
                else
                    Assert.Equal(expectGeneratedLink ? generatedPath : "Main.cs", sourcePaths[0]);
                if (outputFormat == "apiPage")
                {
                    var heading = content.Split("- facts:", 2)[0];
                    if (allExcluded)
                        Assert.DoesNotContain("src:", heading);
                    else
                        Assert.Contains("src: https://github.com/dotnet/docfx/blob/main/" + (expectGeneratedLink ? generatedPath : "Main.cs"), heading);
                    Assert.Equal(!allExcluded, content.Contains("https://github.com/dotnet/docfx/blob/main/Main.cs"));
                    Assert.Equal(expectGeneratedLink, content.Contains("https://github.com/dotnet/docfx/blob/main/" + generatedPath));
                }
            }
        }
    }

    private static void RunGit(string folder, string arguments)
    {
        using var stdout = new MemoryStream();
        using var stderr = new MemoryStream();
        using var stdoutWriter = new StreamWriter(stdout);
        using var stderrWriter = new StreamWriter(stderr);
        var exitCode = CommandUtility.RunCommand(new()
        {
            Name = "git",
            Arguments = arguments,
            WorkingDirectory = folder,
        }, stdoutWriter, stderrWriter);
        stdoutWriter.Flush();
        stderrWriter.Flush();
        Assert.True(exitCode == 0, Encoding.UTF8.GetString(stderr.ToArray()));
    }
}
