---
# Support schema documents in YAML format
inputs:
  docfx.yml:
  docs/a.yml: |
    #YamlMime:LandingData
    title: my title
    metadata:
      key: value
outputs:
  docs/a.json: |
    {
      "content": { "title": "my title" },
      "metadata": { "key": "value" }
    }
  build.manifest:
---
# Support schema documents in JSON format
inputs:
  docfx.yml:
  docs/a.json: |
    {
      "$schema": "https://raw.githubusercontent.com/dotnet/docfx/v3/schemas/LandingData.json",
      "title": "my title",
      "metadata": { "key": "value" }
    }
outputs:
  docs/a.json: |
    { 
      "content": { "title": "my title" },
      "metadata": { "key": "value" }
    }
  build.manifest:
---
# Throw error when schema is not specified
inputs:
  docfx.yml:
  docs/a.yml: |
    title: my title
outputs:
  build.manifest:
  build.log: |
   ["error","schema-not-found","Unknown schema ''","docs/a.yml"]
---
# Fallback to documentType when yaml mime is YamlDocument
inputs:
  docfx.yml:
  docs/a.yml: |
    #YamlMime:YamlDocument
    documentType: LandingData
    title: my title
outputs:
  docs/a.json: |
    {
      "content": { "title": "my title" }
    }
  build.manifest:
---
# Support schema documents with Href content
inputs:
  docfx.yml:
  # TODO: why is there no output for this toc file?
  TOC.yml:
  docs/TOC.yml:
  docs/a.yml: |
    #YamlMime:ContextObject
    brand: azure
    breadcrumb_path: TOC.yml
    toc_rel: ../TOC.yml
outputs:
  docs/TOC.json:
  docs/a.json: |
    {
      "content": { "brand": "azure", "breadcrumb_path": "TOC.json", "toc_rel": "../TOC.json" },
    }
  build.manifest:
---
# schema documents with Href content but wrong type
inputs:
  docfx.yml:
  # TODO: why is there no output for this toc file?
  TOC.yml:
  docs/TOC.yml:
  docs/a.yml: |
    #YamlMime:ContextObject
    brand: azure
    breadcrumb_path: 1
    toc_rel: ../TOC.yml
outputs:
  docs/TOC.json:
  build.manifest:
  build.log: |
   ["error","violate-schema","Field with attribute 'Microsoft.Docs.Build.HrefAttribute' should be of type System.String.","docs/a.yml",3,18]
---
# Support schema documents with Markdown content
inputs:
  docfx.yml:
  docs/a.yml: |
    #YamlMime:MarkdownTestModel
    description: Hello `docfx`!
outputs:
  build.manifest:
  docs/a.json: |
    { "content": { "description": "<p>Hello <code>docfx</code>!</p>" } }
---
# Markdown content with null value
inputs:
  docfx.yml:
  docs/a.yml: |
    #YamlMime:MarkdownTestModel
    description:
outputs:
  build.manifest:
  docs/a.json: |
    { "content": {} }
  build.log: |
    ["info","null-value","'description' contains null value","docs/a.yml",2,1]
---
