USE [test]
GO

/****** Object:  Table [dbo].[uidt]    Script Date: 7/21/2017 9:13:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[uidt](
	[uid] [varchar](800) NOT NULL,
	[objectStr] [varchar](max) NOT NULL,
 CONSTRAINT [PK_uidt] PRIMARY KEY CLUSTERED 
(
	[uid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
