name: nightly
on:
  schedule:
  - cron: '0 0 * * *'

env:
  DOCFX_PREVIEW_BUILD: true

jobs:
  publish-github-packages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
 
    - id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        version_format: ${major}.${minor}.${patch}-preview.${increment}

    - uses: ./.github/actions/build

    - name: dotnet test
      id: test-net90
      run: dotnet test -c Release -f net9.0 --no-build

    - name: Report failed tests
      if: ${{ failure() && steps.test-net90.outcome == 'failure' }}
      uses: ./.github/actions/report-failed-tests
    
    - name: dotnet pack
      run: dotnet pack -c Release /p:Version=${{ steps.version.outputs.version }} /p:ApiCompatGenerateSuppressionFile=true -o drop/nuget

    - name: dotnet nuget push
      run: |
        dotnet nuget push drop/nuget/*.nupkg --api-key "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate --source https://nuget.pkg.github.com/dotnet/index.json

