name: pr
on:
  issue_comment:
    types: [created]

jobs:
  update-snapshot:
    if: ${{ github.event.comment.body == '/update-snapshot'}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ github.event.issue.number }}/head
        lfs: true

    - uses: ./.github/actions/build

    - run: dotnet test -c Release --filter Stage=Snapshot --no-build
      working-directory: test/docfx.Snapshot.Tests
      env:
        UPDATE_SNAPSHOT: true

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'test(snapshot): update snapshots for ${{ github.sha }}'