name: pr
on:
  issue_comment:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: khan/pull-request-comment-trigger@v1.1.0
      id: update-snapshot
      with:
        trigger: '/update-snapshot'
        reaction: rocket
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    outputs:
      update-snapshot: steps.check.update-snapshot.triggered == 'true'

  update-snapshot:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.update-snapshot
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        lfs: true

    - uses: ./.github/actions/build

    - run: dotnet test -c Release --filter Stage=Snapshot --no-build
      working-directory: test/docfx.Snapshot.Tests
      env:
        UPDATE_SNAPSHOT: true

    - run: |
        git config --global user.name docfx
        git config --global user.email "docfx@users.noreply.github.com"
        git commit -a -m "test(snapshot): update snapshots for $GITHUB_SHA"
        git push
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
