name: Spell Check
on:
  push:
    branches: [ v3 ]
  pull_request:
    branches: [ v3 ]
jobs:
  build:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - uses: check-spelling/check-spelling@main
      with:
        experimental_apply_changes_via_bot: 1
